# Generated by Django 4.1.7 on 2023-03-17 13:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_resume_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='others',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
